"""
Utilities for analysing chains generated by MCMC or ABC algorithms. Provides pair plots, convergence diagnostics and helper tools.
"""

"""
    ChainPairPlots(chain, params; prior=nothing, burnin=0, title="", saveplot=false, savestring="", symbols=nothing)

Create pair plots for MCMC chain samples.

# Arguments
- `chain`: MCMCChains.Chains object or distribution (e.g., from VI)
- `params`: Vector of reference parameter values (e.g., optimal parameters)
- `prior`: Prior distribution (any Distributions.jl compatible distribution, or nothing)
- `burnin`: Number of initial samples to discard (default: 0)
- `title`: Plot title
- `saveplot`: Whether to save the plot
- `savestring`: Filename for saving
- `symbols`: Vector of Symbols for parameter names (optional, overrides extraction from chain)

# Example
```julia
prior = product_distribution([TriangularDist(lb[i], ub[i], mode[i]) for i in 1:4])
ChainPairPlots(chain, optimalparameters; prior=prior, burnin=1024)

# For VI results with custom parameter names
ChainPairPlots(vi_result, optimalparameters;
               prior=prior,
               symbols=[:ln_nucleation_prefactor, :surface_energy,
                         :growth_coefficient, :growth_order])
```
"""

"""
    _normalize_symbols(symbols::Union{Vector{Symbol}, Nothing}, n_params::Int) -> Union{Vector{Symbol}, Nothing}

Normalize parameter symbols to match the expected parameter count.

# Arguments
- `symbols::Union{Vector{Symbol}, Nothing}`: Input symbols or nothing
- `n_params::Int`: Expected number of parameters

# Returns
- `Union{Vector{Symbol}, Nothing}`: Normalized symbols matching n_params, or nothing if input was nothing

If symbols is shorter than n_params, pads with :param_i symbols.
If symbols is longer, truncates to n_params.
"""
function _normalize_symbols(symbols::Union{Vector{Symbol}, Nothing}, n_params::Int)
    symbols === nothing && return nothing
    if length(symbols) == n_params
        return symbols
    elseif length(symbols) > n_params
        return symbols[1:n_params]
    end
    extra = [Symbol("param_$i") for i in (length(symbols) + 1):n_params]
    return vcat(symbols, extra)
end

function ChainPairPlots(chain, params::Vector{Float64};
                        prior::Union{Distributions.Distribution, Nothing} = nothing,
                        burnin::Int = 0,
                        title = "",
                        show_title::Bool = true,
                        saveplot::Bool = false,
                        savestring::String = "",
                        savedir::Union{Nothing, AbstractString} = nothing,
                        symbols::Union{Vector{Symbol}, Nothing} = nothing,
                        showplot::Bool = true)
    # Determine parameter symbols and extraction names
    if isa(chain, MCMCChains.Chains)
        chain_param_names = collect(names(chain, :parameters))
        if symbols !== nothing
            if all(s -> s in chain_param_names, symbols)
                extract_symbols = symbols
                label_symbols = symbols
            elseif length(symbols) == length(chain_param_names)
                extract_symbols = chain_param_names
                label_symbols = symbols
            else
                extract_symbols = chain_param_names
                label_symbols = chain_param_names
            end
        else
            extract_symbols = chain_param_names
            label_symbols = chain_param_names
        end

        mean_stats = mean(chain).nt
        mean_map = Dict(collect(mean_stats.parameters)[i] => mean_stats.mean[i]
                        for i in eachindex(mean_stats.mean))
        meanparameter = [mean_map[s] for s in extract_symbols]

        samples_mat = chains_to_matrix(chain, burnin = burnin, params = extract_symbols)
        df = DataFrame(permutedims(samples_mat), label_symbols)

        n_truth = min(length(params), length(label_symbols))
        truth_params = Dict(label_symbols[i] => params[i] for i in 1:n_truth)
        mean_params_dict = Dict(label_symbols[i] => meanparameter[i]
                                for i in eachindex(meanparameter))
    else
        # Fallback: generate generic names for distributions (e.g., VI results)
        param_symbols = symbols !== nothing ? symbols :
                        [Symbol("param_$i") for i in eachindex(params)]
        meanparameter = params  # For distributions, use params directly

        samples_mat = chains_to_matrix(chain, burnin = burnin, params = param_symbols)
        df = DataFrame(permutedims(samples_mat), param_symbols)

        n_truth = min(length(params), length(param_symbols))
        truth_params = Dict(param_symbols[i] => params[i] for i in 1:n_truth)
        mean_params_dict = Dict(param_symbols[i] => meanparameter[i]
                                for i in eachindex(meanparameter))
    end

    if prior !== nothing
        # Accept any Distribution directly - use utility function
        priordist_matrix = distribution_to_matrix(prior, CRISTOOL_PRIOR_PLOT_SAMPLES)
        if size(priordist_matrix, 1) == length(names(df))
            prior_df = DataFrame(permutedims(priordist_matrix), names(df))
        else
            @warn "Prior dimension mismatch for pairplot; skipping prior overlay" prior_dim = size(priordist_matrix, 1) df_dim = length(names(df))
            prior_df = DataFrame()
        end
    else
        prior_df = DataFrame()
    end

    plot_posterior_pairplot(df, prior_df, truth_params, mean_params_dict;
                            title = show_title ? title : "",
                            savename = savestring,
                            savedir = savedir,
                            showplot = showplot)
end

"""
    ChainPairPlots(samples::AbstractMatrix, params::Vector{Float64};
                   prior=nothing, burnin::Int=0, title="", saveplot::Bool=false,
                   savestring::String="", symbols=nothing, showplot::Bool=true)

Create pair plots from a raw sample matrix.

# Arguments
- `samples::AbstractMatrix`: Parameter samples of size (n_params, n_samples)
- `params::Vector{Float64}`: Reference parameter values (e.g., optimal parameters)
- `prior::Union{Distribution, Nothing}=nothing`: Prior distribution for overlay
- `burnin::Int=0`: Number of initial samples to discard
- `title=""`: Plot title
- `saveplot::Bool=false`: Whether to save the plot
- `savestring::String=""`: Filename for saving
- `symbols::Union{Vector{Symbol}, Nothing}=nothing`: Parameter names
- `showplot::Bool=true`: Whether to display the plot

# Example
```julia
samples = rand(4, 1000)  # 4 parameters, 1000 samples
ChainPairPlots(samples, optimalparameters;
               symbols=[:ln_nucleation_prefactor, :surface_energy,
                         :growth_coefficient, :growth_order])
```
"""
function ChainPairPlots(samples::AbstractMatrix, params::Vector{Float64};
                        prior::Union{Distributions.Distribution, Nothing} = nothing,
                        burnin::Int = 0,
                        title = "",
                        show_title::Bool = true,
                        saveplot::Bool = false,
                        savestring::String = "",
                        savedir::Union{Nothing, AbstractString} = nothing,
                        symbols::Union{Vector{Symbol}, Nothing} = nothing,
                        showplot::Bool = true)
    n_params = size(samples, 1)
    param_symbols = symbols !== nothing ? symbols : [Symbol("param_$i") for i in 1:n_params]
    param_symbols = _normalize_symbols(param_symbols, n_params)

    samples_mat = burnin > 0 ? samples[:, (burnin + 1):end] : samples
    meanparameter = vec(mean(samples_mat, dims = 2))

    df = DataFrame(permutedims(samples_mat), param_symbols)

    truth_params = Dict(param_symbols[i] => params[i] for i in 1:n_params)
    mean_params_dict = Dict(param_symbols[i] => meanparameter[i] for i in 1:n_params)

    if prior !== nothing
        priordist_matrix = distribution_to_matrix(prior, CRISTOOL_PRIOR_PLOT_SAMPLES)
        if size(priordist_matrix, 1) == length(param_symbols)
            prior_df = DataFrame(permutedims(priordist_matrix), param_symbols)
        else
            @warn "Prior dimension mismatch for pairplot; skipping prior overlay" prior_dim = size(priordist_matrix, 1) df_dim = length(param_symbols)
            prior_df = DataFrame()
        end
    else
        prior_df = DataFrame()
    end

    plot_posterior_pairplot(df, prior_df, truth_params, mean_params_dict;
                            title = show_title ? title : "",
                            savename = savestring,
                            savedir = savedir,
                            showplot = showplot)
end



function _mcmcchain_to_flexichain(chain::MCMCChains.Chains)
    params = collect(names(chain, :parameters))
    niters = size(chain.value, 1)
    nchains = size(chain.value, 3)
    dict = Dict{FlexiChains.ParameterOrExtra{Symbol}, Matrix{Float64}}()
    for (j, p) in enumerate(params)
        dict[FlexiChains.Parameter(p)] = chain.value[:, j, :]
    end
    return FlexiChains.FlexiChain{Symbol}(niters, nchains, dict)
end

"""
    ChainStatsPlots(chain; burnin=0, title="", show_title=true, saveplot=false,
                    savestring="", savedir=nothing, showplot=true)

Create trace and density plots for MCMC chain diagnostics (Makie backend).

# Arguments
- `chain`: `MCMCChains.Chains` object.
- `burnin`: number of initial iterations to discard.
- `title`, `show_title`: figure title controls.
- `saveplot`, `savestring`, `savedir`: save the figure to
  `joinpath(savedir, savestring * " ChDensity.png")`. With `saveplot=true`
  and `savedir=nothing` the figure is not saved.
- `showplot`: display the figure.

# Returns
The generated `Makie.Figure`.
"""
function ChainStatsPlots(chain::MCMCChains.Chains;
                         burnin::Int = 0,
                         title = "",
                         show_title::Bool = true,
                         saveplot::Bool = false,
                         savestring::String = "",
                         savedir::Union{Nothing, AbstractString} = nothing,
                         showplot::Bool = true)

    chain_subset = burnin > 0 ? chain[(burnin + 1):end, :, :] : chain
    fc = _mcmcchain_to_flexichain(chain_subset)
    param_names = collect(names(chain_subset, :parameters))
    n_params = length(param_names)

    fig = Makie.Figure(size = (1000, 260 * n_params))
    if show_title && !isempty(title)
        Makie.Label(fig[0, :], title)
    end

    for (i, param) in enumerate(param_names)
        ax_trace = Makie.Axis(fig[i, 1])
        FlexiChains.mtraceplot!(ax_trace, fc, param)
        if i < n_params
            Makie.hidexdecorations!(ax_trace; grid = false)
        else
            ax_trace.xlabel = "Iteration"
        end

        ax_density = Makie.Axis(fig[i, 2])
        Makie.density!(ax_density, fc, param)
        Makie.hideydecorations!(ax_density)
        if i < n_params
            Makie.hidexdecorations!(ax_density; grid = false)
        else
            ax_density.xlabel = "Parameter estimate"
        end
    end

    if saveplot && savedir !== nothing
        outdir = String(savedir)
        mkpath(outdir)
        Makie.save(joinpath(outdir, "$(savestring) ChDensity.png"), fig, px_per_unit = 3)
    end

    if showplot
        display(fig)
    end

    return fig
end

"""
    ChainMeasurementPlots(chain, measurements, params, lossfunction, nucleationfunction,
                          growthfunction, aggregationfunction, breakagefunction, solver;
                 burnin=0, title="", saveplot=false, savestring="", colouroffset=0,
                 showplot=true)

Create plots comparing ensemble simulations from chain samples against measurements.
"""
function ChainMeasurementPlots(chain, measurements::Vector{<:AbstractExperiment},
                               params::Vector{Float64},
                               lossfunction::AbstractPELossFunction,
                               nucleationfunction::AbstractNucleationFunction,
                               growthfunction::AbstractGrowthFunction,
                               aggregationfunction::AbstractAggregationFunction,
                               breakagefunction::AbstractBreakageFunction,
                               solver::AbstractSolver;
                               diss::AbstractDissolutionFunction = nodissolution(),
                               burnin::Int = 0,
                               title = "",
                               saveplot::Bool = false,
                               savestring::String = "",
                               savedir::Union{Nothing, AbstractString} = nothing,
                               colouroffset::Int = 0,
                               showplot::Bool = true)

    # Apply burnin if specified
    chain_subset = burnin > 0 ? chain[(burnin + 1):end, :, :] : chain

    meanparameter = mean(chain_subset).nt.mean

    # Use standardized chain conversion
    samples_mat = chains_to_matrix(chain, burnin = burnin)

    ensembleresults = run_ensemble(samples_mat, measurements, nucleationfunction,
                                   growthfunction, aggregationfunction, breakagefunction,
                                   solver; diss = diss)

    optimal_solutions = [(runsimulation(meanparameter,
                                                 nucl = nucleationfunction,
                                                 gr = growthfunction,
                                                 diss = diss,
                                                 agg = aggregationfunction,
                                                 br = breakagefunction,
                                                 initial_concentration = initial_concentration(measurements[m]),
                                                 solver = solver,
                                                 save_idx = ensembleresults[m].time,
                                                 temp_profile = ConstantTemperature(measurements[m].temperature)))
                         for m in eachindex(measurements)]

    plot_measurements_vs_ensemble(measurements, ensembleresults, optimal_solutions;
                                  title = title, savename = savestring,
                                  savedir = savedir,
                                  colouroffset = colouroffset,
                                  parameters = meanparameter,
                                  nucleationfunction = nucleationfunction,
                                  growthfunction = growthfunction,
                                  dissolutionfunction = diss,
                                  aggregationfunction = aggregationfunction,
                                  breakagefunction = breakagefunction, solver = solver,
                                  parameter_samples = samples_mat,
                                  showplot = showplot)
end

# ============================================================================ #
#                    Bayesian inference entry points                           #
# ============================================================================ #

"""
    nuts_model(experiments, prior, nucleationfunction, growthfunction,
               aggregationfunction, breakagefunction;
               solver, lossfunction) -> DynamicPPL.Model

Build a ready-to-sample Turing `DynamicPPL.Model` for MCMC parameter
inference. The model samples `θ[i] ~ prior[i]` for each parameter and
adds the negative loss as the log-joint term, so

    chain = Turing.sample(nuts_model(...), NUTS(1000, 0.65), 1000)

runs NUTS over the same loss that `PE_Routine`/`run_abc` use.

# Arguments
- `experiments::Vector{<:AbstractExperiment}`: data the loss is evaluated on.
- `prior::Vector{<:Distributions.Distribution}`: one prior per parameter
  (e.g. `[TriangularDist(lb[i], ub[i], optpara[i]) ...]` or `Uniform`s).
- `nucleationfunction`, `growthfunction`, `aggregationfunction`,
  `breakagefunction`: kinetic models; their `paramaxis` order defines the
  parameter vector layout.
- `diss`: optional independent dissolution model; its parameter block follows
  the growth block.
- `solver::AbstractSolver`: numerical solver used by the loss.
- `lossfunction::AbstractPELossFunction`: loss used as the likelihood term.

The `LossSetup` (per-experiment `ODEProblem` templates) is built once here
and reused by every sampler evaluation. Chain parameter names are `θ[1]`,
`θ[2]`, …; use [`rename_chain`](@ref) with [`kinetic_parameter_symbols`](@ref)
to give them the kinetic symbols.
"""
function nuts_model(experiments::Vector{<:AbstractExperiment},
                    prior::Vector{<:Distributions.Distribution},
                    nucleationfunction::AbstractNucleationFunction,
                    growthfunction::AbstractGrowthFunction,
                    aggregationfunction::AbstractAggregationFunction,
                    breakagefunction::AbstractBreakageFunction;
                    diss::AbstractDissolutionFunction = nodissolution(),
                    solver::AbstractSolver,
                    lossfunction::AbstractPELossFunction)
    length(prior) == _total_nparams(nucleationfunction, growthfunction,
                                    aggregationfunction, breakagefunction; diss = diss) ||
        throw(ArgumentError("nuts_model: length(prior) = $(length(prior)) does not match " *
                            "the total kinetic parameter count. Supply one prior per parameter."))
    problem = _build_loss_problem(nucleationfunction, growthfunction,
                                  aggregationfunction, breakagefunction, solver;
                                  diss = diss)
    setup = prepare_loss(problem, experiments)
    # MCMCThreads may evaluate chains in independent tasks.  Each chain gets
    # one private LossSetup from a task-local memo, avoiding a deep copy for
    # every NUTS transition.  Each loss evaluation still remakes its
    # ODEProblem from that chain-local template.
    setup_per_task = _cristool_once_per_task(LossSetup) do
        deepcopy(setup)
    end
    return _cristool_nuts_loss_model(prior, lossfunction, setup_per_task)
end

"""Build a task-local memoized initializer of element type `T`.

Julia >= 1.12 ships `Base.OncePerTask`, so this returns the native object
directly (zero custom code, explicit `T`).  On the 1.10/1.11 LTS floor that
type is absent (no Compat backport either), so it falls back to an
identical port: Base's own implementation of `OncePerTask` is exactly
`get!(f, task_local_storage(), self)::T` keyed by the object.

`T` is passed explicitly (never inferred) so the model's
`loss_setup_per_task()` call site - which runs once per NUTS
log-probability evaluation - stays type stable on every supported Julia.
"""
function _cristool_once_per_task(initializer, ::Type{T}) where {T}
    if isdefined(Base, :OncePerTask)
        return Base.OncePerTask{T}(initializer)
    end
    return _CristoolOncePerTask{T, typeof(initializer)}(initializer)
end

"""Task-local memoized initializer, ported from `Base.OncePerTask` (1.12+)."""
struct _CristoolOncePerTask{T, F}
    initializer::F
end
@inline function (_opt::_CristoolOncePerTask{T, F})() where {T, F}
    get!(_opt.initializer, task_local_storage(), _opt)::T
end

# Module-scope Turing model (DynamicPPL requirement). Generic over the
# number of parameters; the per-task loss setup is hoisted out of the model.
Turing.@model function _cristool_nuts_loss_model(prior, lossfunction,
                                                 loss_setup_per_task)
    n = length(prior)
    θ = Vector{Float64}(undef, n)
    for i in 1:n
        θ[i] ~ prior[i]
    end
    Turing.@addlogprob!(-loss(lossfunction, loss_setup_per_task(), θ))
end

"""
    kinetic_parameter_symbols(nucleationfunction, growthfunction,
                              aggregationfunction, breakagefunction;
                              diss=nodissolution()) -> Vector{Symbol}

Parameter symbols for the combined kinetic models, in `paramaxis` order:
the kinetics' own `symbols` where defined, else `:nu1`, `:gr1`, `:diss1`,
`:agg1`, `:br1`, … placeholders. Used to name MCMC chain columns.
"""

"""
    rename_chain(chain::MCMCChains.Chains, symbols::Vector{Symbol}) -> Chains

Rename the parameter columns of an MCMC chain in place of a new vector of
symbols (e.g. from [`kinetic_parameter_symbols`](@ref)). The chain must
contain exactly `length(symbols)` parameters.
"""
function rename_chain(chain::MCMCChains.Chains, symbols::Vector{Symbol})
    old_names = collect(chain.name_map.parameters)
    length(old_names) == length(symbols) ||
        throw(ArgumentError("rename_chain: chain has $(length(old_names)) parameters but " *
                            "$(length(symbols)) symbols were given."))
    rename_dict = Dict(old_names[i] => symbols[i] for i in eachindex(old_names))
    return MCMCChains.replacenames(chain, rename_dict)
end

"""
    MCMC_Routine(measurements, prior, nucleationfunction, growthfunction,
                 aggregationfunction, breakagefunction;
                 solver, lossfunction, sampler = NUTS(1000, 0.65;
                 adtype = AutoForwardDiff(chunksize = 4)), n_samples = 1000,
                 n_chains = 4, burnin = 0, extrastring = "Empty",
                 symbols = nothing, outputdir = nothing, saveplot = true,
                 showplot = false, verbosity = 1) -> Chains

Full Bayesian inference routine mirroring `run_abc`: builds the model via
[`nuts_model`](@ref), samples with `sampler` (default NUTS with ForwardDiff
AD), renames the chain with the inferred kinetic symbols, and returns the
named chain.

# Arguments
- `measurements::Vector{<:AbstractExperiment}`: data used for the loss.
- `prior::Vector{<:Distributions.Distribution}`: one prior per parameter.
- `nucleationfunction`, `growthfunction`, `aggregationfunction`,
  `breakagefunction`: kinetic models.
- `solver::AbstractSolver`, `lossfunction::AbstractPELossFunction`:
  forward model and discrepancy.
- `sampler`: any AbstractMCMC sampler (default `NUTS(1000, 0.65;
  adtype=AutoForwardDiff(chunksize=4))`; the first argument is the
  adaptation length).
- `n_samples`: retained samples per chain.
- `n_chains`: number of parallel chains (via `MCMCThreads()`).
- `burnin`: initial iterations discarded from plots/summaries.
- `symbols`: optional parameter names; defaults to
  `kinetic_parameter_symbols(...)` from the kinetics.
- `outputdir`: where to persist results. `nothing` (default) performs no
  filesystem writes; otherwise the named chain (`.jld2`), and — when
  `saveplot` is true — posterior pair, trace/density and
  measurements-vs-ensemble plots are written there.
- `showplot`: display generated diagnostics; defaults to `false` for a
  headless routine.
- `verbosity`: 0 silent, 1 normal, 2 verbose.

# Returns
The renamed `MCMCChains.Chains` (post-burnin when `burnin > 0`).
"""
function MCMC_Routine(measurements::Vector{<:AbstractExperiment},
                      prior::Vector{<:Distributions.Distribution},
                      nucleationfunction::AbstractNucleationFunction,
                      growthfunction::AbstractGrowthFunction,
                      aggregationfunction::AbstractAggregationFunction,
                      breakagefunction::AbstractBreakageFunction;
                      diss::AbstractDissolutionFunction = nodissolution(),
                      solver::AbstractSolver,
                      lossfunction::AbstractPELossFunction,
                      sampler = Turing.NUTS(1000, 0.65;
                                            adtype = Turing.AutoForwardDiff(chunksize = 4)),
                      n_samples::Int = 1000,
                      n_chains::Int = 4,
                      burnin::Int = 0,
                      extrastring::String = "Empty",
                      symbols::Union{Nothing, Vector{Symbol}} = nothing,
                      outputdir::Union{Nothing, AbstractString} = nothing,
                      saveplot::Bool = true,
                      showplot::Bool = false,
                      verbosity::Int = 1)
    nparams = _total_nparams(nucleationfunction, growthfunction,
                             aggregationfunction, breakagefunction; diss = diss)
    length(prior) == nparams ||
        throw(ArgumentError("MCMC_Routine: length(prior) = $(length(prior)) does not " *
                            "match the total kinetic parameter count ($nparams)."))

    inferred_symbols = isnothing(symbols) ?
                       kinetic_parameter_symbols(nucleationfunction, growthfunction,
                                                 aggregationfunction, breakagefunction;
                                                 diss = diss) :
                       symbols
    length(inferred_symbols) == nparams ||
        throw(ArgumentError("MCMC_Routine: $(length(inferred_symbols)) symbols given for " *
                            "$nparams parameters."))

    start_content = build_mcmc_start_content(prior, sampler, n_samples, n_chains,
                                             lossfunction, solver, nucleationfunction,
                                             growthfunction, aggregationfunction,
                                             breakagefunction;
                                             extrastring = extrastring,
                                             symbols = inferred_symbols)
    print_start_panel("MCMC", start_content; verbosity = verbosity)

    model = nuts_model(measurements, prior, nucleationfunction, growthfunction,
                       aggregationfunction, breakagefunction;
                       diss = diss,
                       solver = solver, lossfunction = lossfunction)

    chain = Turing.sample(model, sampler, Turing.MCMCThreads(), n_samples, n_chains;
                          progress = verbosity > 1)
    named_chain = rename_chain(chain, inferred_symbols)
    if burnin > 0
        named_chain = named_chain[(burnin + 1):end, :, :]
    end

    end_content = build_mcmc_end_content(named_chain)
    print_end_panel("MCMC", end_content; verbosity = verbosity)

    if outputdir !== nothing
        outdir = String(outputdir)
        mkpath(outdir)
        now_str = Dates.format(now(), "yy-m-d HH-MM")
        jldsave(joinpath(outdir, "$(now_str) $(extrastring).jld2");
                chain = named_chain, sampler = sampler, prior = prior)

        if saveplot
            meanparameter = mean(named_chain).nt.mean
            ChainPairPlots(named_chain, meanparameter; prior = product_distribution(prior...),
                           burnin = 0, title = "$(now_str) $(extrastring)\nMCMC posterior",
                           saveplot = true, savestring = "$(now_str) $(extrastring)",
                           savedir = outdir, symbols = inferred_symbols,
                           showplot = showplot)
            ChainStatsPlots(named_chain; title = "$(now_str) $(extrastring)",
                            saveplot = true, savestring = "$(now_str) $(extrastring)",
                            savedir = outdir, showplot = showplot)
            ChainMeasurementPlots(named_chain, measurements, meanparameter,
                                  lossfunction, nucleationfunction, growthfunction,
                                  aggregationfunction, breakagefunction, solver;
                                  diss = diss,
                                  burnin = 0, title = "$(now_str) $(extrastring)",
                                  saveplot = true,
                                  savestring = "$(now_str) $(extrastring)",
                                  savedir = outdir, showplot = showplot)
        end
    end

    return named_chain
end

_total_nparams(nucl, gr, agg, br; diss = nodissolution()) =
    _nparams_of(nucl) + _nparams_of(gr) + _nparams_of(diss) +
    _nparams_of(agg) + _nparams_of(br)

_nparams_of(fn) = hasproperty(fn, :nparams) ? getproperty(fn, :nparams) : 0
