[deps]
CriSTool = "85fc7edd-a5b7-4e55-9de4-f5475cce2f08"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"

[sources]
CriSTool = {path = ".."}

[compat]
CriSTool = "0.1"
Documenter = "1"
DocumenterVitepress = "0.3"
julia = "^1.10"
