"""
Utilities for analysing chains generated by MCMC or ABC algorithms. Provides pair plots, convergence diagnostics and helper tools.
"""

"""
    ChainPairPlots(chain, params; prior=nothing, burnin=0, title="", saveplot=false, savestring="", symbols=nothing)

Create pair plots for MCMC chain samples.

# Arguments
- `chain`: MCMCChains.Chains object or distribution (e.g., from VI)
- `params`: Vector of reference parameter values (e.g., optimal parameters)
- `prior`: Prior distribution (any Distributions.jl compatible distribution, or nothing)
- `burnin`: Number of initial samples to discard (default: 0)
- `title`: Plot title
- `saveplot`: Whether to save the plot
- `savestring`: Filename for saving
- `symbols`: Vector of Symbols for parameter names (optional, overrides extraction from chain)

# Example
```julia
prior = product_distribution([TriangularDist(lb[i], ub[i], mode[i]) for i in 1:4])
ChainPairPlots(chain, optimalparameters; prior=prior, burnin=1024)

# For VI results with custom parameter names
ChainPairPlots(vi_result, optimalparameters; prior=prior, symbols=[:Aⱼ, :γ, :Ag, :g])
```
"""

"""
    _normalize_symbols(symbols::Union{Vector{Symbol}, Nothing}, n_params::Int) -> Union{Vector{Symbol}, Nothing}

Normalize parameter symbols to match the expected parameter count.

# Arguments
- `symbols::Union{Vector{Symbol}, Nothing}`: Input symbols or nothing
- `n_params::Int`: Expected number of parameters

# Returns
- `Union{Vector{Symbol}, Nothing}`: Normalized symbols matching n_params, or nothing if input was nothing

If symbols is shorter than n_params, pads with :param_i symbols.
If symbols is longer, truncates to n_params.
"""
function _normalize_symbols(symbols::Union{Vector{Symbol}, Nothing}, n_params::Int)
    symbols === nothing && return nothing
    if length(symbols) == n_params
        return symbols
    elseif length(symbols) > n_params
        return symbols[1:n_params]
    end
    extra = [Symbol("param_$i") for i in (length(symbols) + 1):n_params]
    return vcat(symbols, extra)
end

function ChainPairPlots(chain, params::Vector{Float64};
                        prior::Union{Distributions.Distribution, Nothing} = nothing,
                        burnin::Int = 0,
                        title = "",
                        show_title::Bool = true,
                        saveplot::Bool = false,
                        savestring::String = "",
                        savedir::Union{Nothing, AbstractString} = nothing,
                        symbols::Union{Vector{Symbol}, Nothing} = nothing,
                        showplot::Bool = true)
    # Determine parameter symbols and extraction names
    if isa(chain, MCMCChains.Chains)
        chain_param_names = collect(names(chain, :parameters))
        if symbols !== nothing
            if all(s -> s in chain_param_names, symbols)
                extract_symbols = symbols
                label_symbols = symbols
            elseif length(symbols) == length(chain_param_names)
                extract_symbols = chain_param_names
                label_symbols = symbols
            else
                extract_symbols = chain_param_names
                label_symbols = chain_param_names
            end
        else
            extract_symbols = chain_param_names
            label_symbols = chain_param_names
        end

        mean_stats = mean(chain).nt
        mean_map = Dict(collect(mean_stats.parameters)[i] => mean_stats.mean[i]
                        for i in eachindex(mean_stats.mean))
        meanparameter = [mean_map[s] for s in extract_symbols]

        samples_mat = chains_to_matrix(chain, burnin = burnin, params = extract_symbols)
        df = DataFrame(permutedims(samples_mat), label_symbols)

        n_truth = min(length(params), length(label_symbols))
        truth_params = Dict(label_symbols[i] => params[i] for i in 1:n_truth)
        mean_params_dict = Dict(label_symbols[i] => meanparameter[i]
                                for i in eachindex(meanparameter))
    else
        # Fallback: generate generic names for distributions (e.g., VI results)
        param_symbols = symbols !== nothing ? symbols :
                        [Symbol("param_$i") for i in eachindex(params)]
        meanparameter = params  # For distributions, use params directly

        samples_mat = chains_to_matrix(chain, burnin = burnin, params = param_symbols)
        df = DataFrame(permutedims(samples_mat), param_symbols)

        n_truth = min(length(params), length(param_symbols))
        truth_params = Dict(param_symbols[i] => params[i] for i in 1:n_truth)
        mean_params_dict = Dict(param_symbols[i] => meanparameter[i]
                                for i in eachindex(meanparameter))
    end

    if prior !== nothing
        # Accept any Distribution directly - use utility function
        priordist_matrix = distribution_to_matrix(prior, 2^18)
        if size(priordist_matrix, 1) == length(names(df))
            prior_df = DataFrame(permutedims(priordist_matrix), names(df))
        else
            @warn "Prior dimension mismatch for pairplot; skipping prior overlay" prior_dim = size(priordist_matrix, 1) df_dim = length(names(df))
            prior_df = DataFrame()
        end
    else
        prior_df = DataFrame()
    end

    plot_posterior_pairplot(df, prior_df, truth_params, mean_params_dict;
                            title = show_title ? title : "",
                            savename = savestring,
                            savedir = savedir,
                            showplot = showplot)
end

"""
    ChainPairPlots(samples::AbstractMatrix, params::Vector{Float64};
                   prior=nothing, burnin::Int=0, title="", saveplot::Bool=false,
                   savestring::String="", symbols=nothing, showplot::Bool=true)

Create pair plots from a raw sample matrix.

# Arguments
- `samples::AbstractMatrix`: Parameter samples of size (n_params, n_samples)
- `params::Vector{Float64}`: Reference parameter values (e.g., optimal parameters)
- `prior::Union{Distribution, Nothing}=nothing`: Prior distribution for overlay
- `burnin::Int=0`: Number of initial samples to discard
- `title=""`: Plot title
- `saveplot::Bool=false`: Whether to save the plot
- `savestring::String=""`: Filename for saving
- `symbols::Union{Vector{Symbol}, Nothing}=nothing`: Parameter names
- `showplot::Bool=true`: Whether to display the plot

# Example
```julia
samples = rand(4, 1000)  # 4 parameters, 1000 samples
ChainPairPlots(samples, optimalparameters; symbols=[:Aⱼ, :γ, :Ag, :g])
```
"""
function ChainPairPlots(samples::AbstractMatrix, params::Vector{Float64};
                        prior::Union{Distributions.Distribution, Nothing} = nothing,
                        burnin::Int = 0,
                        title = "",
                        show_title::Bool = true,
                        saveplot::Bool = false,
                        savestring::String = "",
                        savedir::Union{Nothing, AbstractString} = nothing,
                        symbols::Union{Vector{Symbol}, Nothing} = nothing,
                        showplot::Bool = true)
    n_params = size(samples, 1)
    param_symbols = symbols !== nothing ? symbols : [Symbol("param_$i") for i in 1:n_params]
    param_symbols = _normalize_symbols(param_symbols, n_params)

    samples_mat = burnin > 0 ? samples[:, (burnin + 1):end] : samples
    meanparameter = vec(mean(samples_mat, dims = 2))

    df = DataFrame(permutedims(samples_mat), param_symbols)

    truth_params = Dict(param_symbols[i] => params[i] for i in 1:n_params)
    mean_params_dict = Dict(param_symbols[i] => meanparameter[i] for i in 1:n_params)

    if prior !== nothing
        priordist_matrix = distribution_to_matrix(prior, 2^18)
        if size(priordist_matrix, 1) == length(param_symbols)
            prior_df = DataFrame(permutedims(priordist_matrix), param_symbols)
        else
            @warn "Prior dimension mismatch for pairplot; skipping prior overlay" prior_dim = size(priordist_matrix, 1) df_dim = length(param_symbols)
            prior_df = DataFrame()
        end
    else
        prior_df = DataFrame()
    end

    plot_posterior_pairplot(df, prior_df, truth_params, mean_params_dict;
                            title = show_title ? title : "",
                            savename = savestring,
                            savedir = savedir,
                            showplot = showplot)
end

"""
    ChainPairPlots(chain, params::Vector{Float64}, prior::KissABC.Factored{N};
                   burnin::Int=0, title="", saveplot::Bool=false, savestring::String="",
                   symbols=nothing, showplot::Bool=true) where {N}

Create pair plots with a KissABC.Factored prior (deprecated, for backward compatibility).

# Arguments
- `chain`: MCMCChains.Chains object or distribution
- `params::Vector{Float64}`: Reference parameter values
- `prior::KissABC.Factored{N}`: Factored prior distribution (converted to Product internally)
- `burnin::Int=0`: Number of initial samples to discard
- `title=""`: Plot title
- `saveplot::Bool=false`: Whether to save the plot
- `savestring::String=""`: Filename for saving
- `symbols::Union{Vector{Symbol}, Nothing}=nothing`: Parameter names
- `showplot::Bool=true`: Whether to display the plot

Note: This method is deprecated. Use `product_distribution` instead of `Factored`.
"""
function ChainPairPlots(chain, params::Vector{Float64},
                        prior::KissABC.Factored{N};
                        burnin::Int = 0,
                        title = "",
                        show_title::Bool = true,
                        saveplot::Bool = false,
                        savestring::String = "",
                        savedir::Union{Nothing, AbstractString} = nothing,
                        symbols::Union{Vector{Symbol}, Nothing} = nothing,
                        showplot::Bool = true) where {N}
    prod_prior = Distributions.product_distribution([prior.p[i] for i in 1:N])
    return ChainPairPlots(chain, params; prior = prod_prior, burnin = burnin,
                          title = title, show_title = show_title,
                          saveplot = saveplot, savestring = savestring,
                          savedir = savedir,
                          symbols = symbols, showplot = showplot)
end

"""
    ChainStatsPlots(chain; burnin=0, title="", show_title=true, saveplot=false, savestring="")

Create trace and density plots for MCMC chain diagnostics.
"""
function ChainStatsPlots(chain;
                         burnin::Int = 0,
                         title = "",
                         show_title::Bool = true,
                         saveplot::Bool = false,
                         savestring::String = "",
                         showplot::Bool = true)

    # Apply burnin if specified
    chain_subset = burnin > 0 ? chain[(burnin + 1):end, :, :] : chain

    meanparameter = mean(chain_subset).nt.mean
    paranames = mean(chain_subset).nt.parameters

    statplot = StatsPlots.plot(chain_subset, plot_title = show_title ? title : "", plot_titlefontsize = 10)

    if showplot
        display(statplot)
    end

    if saveplot
        StatsPlots.savefig(statplot,
                           joinpath(pwd(), "R - MCMC Results",
                                    "$(savestring) ChDensity.png"))
    end

    return statplot
end

"""
    ChainMeasurementPlots(chain, measurements, params, lossfunction, nucleationfunction,
                          growthfunction, aggregationfunction, breakagefunction, solver;
                          burnin=0, title="", saveplot=false, savestring="", colouroffset=0)

Create plots comparing ensemble simulations from chain samples against measurements.
"""
function ChainMeasurementPlots(chain, measurements::Vector{<:AbstractMeasurements},
                               params::Vector{Float64},
                               lossfunction::AbstractPELossFunction,
                               nucleationfunction::AbstractNucleationFunction,
                               growthfunction::AbstractGrowthFunction,
                               aggregationfunction::AbstractAggregationFunction,
                               breakagefunction::AbstractBreakageFunction,
                               solver::AbstractSolver;
                               burnin::Int = 0,
                               title = "",
                               saveplot::Bool = false,
                               savestring::String = "",
                               colouroffset::Int = 0)

    # Apply burnin if specified
    chain_subset = burnin > 0 ? chain[(burnin + 1):end, :, :] : chain

    meanparameter = mean(chain_subset).nt.mean

    # Use standardized chain conversion
    samples_mat = chains_to_matrix(chain, burnin = burnin)

    ensembleresults = run_ensemble(samples_mat, measurements, nucleationfunction,
                                   growthfunction, aggregationfunction, breakagefunction,
                                   solver)

    optimal_solutions = [(CriSTool.runsimulation(meanparameter,
                                                 nucl = nucleationfunction,
                                                 gr = growthfunction,
                                                 agg = aggregationfunction,
                                                 br = breakagefunction,
                                                 initial_concentration = measurements[m].concentrationmean[1],
                                                 solver = solver,
                                                 save_idx = ensembleresults[m].time,
                                                 temp_profile = ConstantTemperature(measurements[m].temperature)))
                         for m in eachindex(measurements)]

    plot_measurements_vs_ensemble(measurements, ensembleresults, optimal_solutions;
                                  title = title, savename = savestring,
                                  colouroffset = colouroffset,
                                  parameters = meanparameter,
                                  nucleationfunction = nucleationfunction,
                                  growthfunction = growthfunction,
                                  aggregationfunction = aggregationfunction,
                                  breakagefunction = breakagefunction, solver = solver,
                                  parameter_samples = samples_mat)
end
